FROM node:lts-alpine3.23

RUN npm i -g pnpm

WORKDIR /app

ENV NODE_ENV=development
ENV HOSTNAME=0.0.0.0

COPY package.json pnpm-lock.yaml tsconfig.json pnpm-workspace.yaml ./

RUN pnpm i

COPY . .

EXPOSE 3000

CMD [ "pnpm", "run", "dev" ]