name: scafold-post-repo
services:
  db:
    image: bitnami/postgresql:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scafold-db
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
    ports:
      - "5432:5432"
    restart: always
    networks:
      - inner-net
    volumes:
      - db_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # db-replica:  
  #   image: bitnami/postgresql:latest
  #   container_name: db-replica
  #   environment:
  #     POSTGRESQL_USERNAME: postgres
  #     POSTGRESQL_PASSWORD: postgres
  #     POSTGRESQL_REPLICATION_MODE: slave
  #     POSTGRESQL_REPLICATION_USER: repl_user
  #     POSTGRESQL_REPLICATION_PASSWORD: repl_password
  #     POSTGRESQL_MASTER_HOST: db
  #     POSTGRESQL_MASTER_PORT_NUMBER: 5432
  #   ports:
  #     - "5433:5432"
  #   networks:
  #     - inner-net
  #   volumes:
  #     - db_replica_data:/bitnami/postgresql
  #   depends_on:
  #     db:
  #       condition: service_healthy

  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
    restart: always
    networks:
      - inner-net
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p password 'RETURN 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis-client:
    image: redis:7-alpine
    container_name: redis-client
    ports:
      - "6379:6379"
    networks:
      - inner-net
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:4000"
    environment:
      CI: "true"
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/scafold-db
      DATABASE_URL_READ: postgresql://postgres:postgres@db-replica:5432/scafold-db
      REDIS_CLIENT_URL: redis://redis-client:6379
      ACCESS_SECRET: random3233cscsdc
      GOOGLE_CLIENT_ID: <GOOGLE_CLIENT_ID>
      GOOGLE_CLIENT_SECRET: <GOOGLE_CLIENT_SECRET>
      GOOGLE_REDIRECT_URI: http://localhost:4000/api/auth/google/callback
      WEB_APP_URL: http://localhost:3000
      LOG_LEVEL: trace
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    networks:
      - inner-net
    depends_on:
      db:
        condition: service_healthy
      redis-client:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    # command: sh -c "npx prisma migrate dev && npm run dev"

  # web:
  #   build: 
  #     context: ./apps/web
  #     dockerfile: Dockerfile.dev
  #   container_name: web
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     API_BASE_URL: http://api:4000/api
  #     NEXT_PUBLIC_API_BASE_URL: http://localhost:4000/api
  #     REDIS_URL: redis://redis-client:6379
  #     AWS_REGION: 'us-east-1'
  #     AWS_SECRET_MANAGER_SECRET_NAME: 'sampleapp/app-config/dev'
  #     AWS_CLOUDFRONT_DOMAIN: 'https://sample.com'
  #   env_file:
  #     - .env.infra
  #     - ./apps/web/.env.infra
  #   volumes:
  #     - ./apps/web/src:/app/src
  #     - ./apps/web/public:/app/public
  #     - ./apps/web/.env.local:/app/.env.local
  #     - /app/.next
  #     - /app/node_modules
  #   networks:
  #     - inner-net
  #   depends_on:
  #     api:
  #       condition: service_healthy

networks:
  inner-net:

volumes:
  db_data:
  db_replica_data:
  redis_data: