onlyBuiltDependencies:
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
  - unrs-resolver

allowBuilds:
  '@google/genai': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  protobufjs: false
  unrs-resolver: true
